### ISSUE TITLE
Problem using CirrusSearch

### ISSUE THREAD

**Issue by D063520** [wmde/wikibase-release-pipeline#286]
Hi,

when I run the docker container out of the box and I try to reindex using CirrusSearch:

 `docker exec -it wikibase_container_name /bin/bash `
 `cd /var/www/html/extensions/CirrusSearch/maintenance`  
```
php ForceSearchIndex.php --fromId 1 --toId 100
ConfigException from line 137 of /var/www/html/includes/config/ConfigFactory.php: No registered builder available for CirrusSearch.
#0 /var/www/html/extensions/CirrusSearch/includes/Maintenance/Maintenance.php(126): ConfigFactory->makeConfig('CirrusSearch')
#1 /var/www/html/extensions/CirrusSearch/maintenance/ForceSearchIndex.php(374): CirrusSearch\Maintenance\Maintenance->getSearchConfig()
#2 /var/www/html/extensions/CirrusSearch/maintenance/ForceSearchIndex.php(141): CirrusSearch\Maintenance\ForceSearchIndex->simpleCheckIndexes()
#3 /var/www/html/maintenance/doMaintenance.php(107): CirrusSearch\Maintenance\ForceSearchIndex->execute()
#4 /var/www/html/extensions/CirrusSearch/maintenance/ForceSearchIndex.php(678): require_once('/var/www/html/m...')
#5 {main}
```

I get the error above. This was not the case with the previews repo https://github.com/wmde/wikibase-docker. Could you check?

**Comment by toban** [comment]
Running it from `/var/www/html/` works fine

```
root@3cbb449dea97:/var/www/html# php /var/www/html/extensions/CirrusSearch/maintenance/ForceSearchIndex.php 
[             my_wiki] Indexed 9 pages ending at 10 at 84/second
[             my_wiki] Indexed 10 pages ending at 20 at 133/second
[             my_wiki] Indexed 10 pages ending at 30 at 165/second
[             my_wiki] Indexed 10 pages ending at 41 at 187/second
Indexed a total of 39 pages at 187/second
root@3cbb449dea97:/var/www/html# cd extensions/CirrusSearch/
root@3cbb449dea97:/var/www/html/extensions/CirrusSearch# php     
.eslintrc.json      .phpcs.xml          CODE_OF_CONDUCT.md  CREDITS             Gruntfile.js        README              composer.json       docs/               i18n/               maintenance/        package.json        resources/          tests/
.phan/              .stylelintrc.json   COPYING             Doxyfile            Makefile            UPGRADE             data/               extension.json      includes/           package-lock.json   profiles/           scripts/            
root@3cbb449dea97:/var/www/html/extensions/CirrusSearch# php 
.eslintrc.json      .phpcs.xml          CODE_OF_CONDUCT.md  CREDITS             Gruntfile.js        README              composer.json       docs/               i18n/               maintenance/        package.json        resources/          tests/
.phan/              .stylelintrc.json   COPYING             Doxyfile            Makefile            UPGRADE             data/               extension.json      includes/           package-lock.json   profiles/           scripts/            
root@3cbb449dea97:/var/www/html/extensions/CirrusSearch# php maintenance/ForceSearchIndex.php 
ConfigException from line 137 of /var/www/html/includes/config/ConfigFactory.php: No registered builder available for CirrusSearch.
#0 /var/www/html/extensions/CirrusSearch/includes/Maintenance/Maintenance.php(126): ConfigFactory->makeConfig('CirrusSearch')
#1 /var/www/html/extensions/CirrusSearch/maintenance/ForceSearchIndex.php(374): CirrusSearch\Maintenance\Maintenance->getSearchConfig()
#2 /var/www/html/extensions/CirrusSearch/maintenance/ForceSearchIndex.php(141): CirrusSearch\Maintenance\ForceSearchIndex->simpleCheckIndexes()
#3 /var/www/html/maintenance/doMaintenance.php(107): CirrusSearch\Maintenance\ForceSearchIndex->execute()
#4 /var/www/html/extensions/CirrusSearch/maintenance/ForceSearchIndex.php(678): require_once('/var/www/html/m...')
#5 {main}

```

**Comment by D063520** [comment]
a bit strange but fine for me! Thank you!
